stages:
  - test
  - deploy

variables:

  AWS_DEFAULT_REGION: 'us-east-1'
  S3_BUCKET: 'tcastel-object-detection'  

deployement:
  stage: deploy
  image: node:latest
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --bucket_name $S3_BUCKET --verbose
  environment: production


unit-test:
  stage: test
  image: python:3.7.5-alpine3.10
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y build-essential 
    - sudo apt-get install -y manpages-dev
    - gcc --version
    #- yum update -y
    #- yum install -y libsm6 libxext6 libxrender-dev
    - python --version
    #- yum install python3 -y
    - pip install virtualenv
    - virtualenv -p python venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - python3 tests.py

  