stages:
  - test
  - deploy

variables:

  AWS_DEFAULT_REGION: 'us-east-1'
  S3_BUCKET: 'tcastel-object-detection'  

deployement:
  stage: deploy
  image: node:latest
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --bucket_name $S3_BUCKET --verbose
  environment: production


unit-test:
  stage: test
  image: python:3.7.5
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv -p python venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - python3 tests.py

  