stages:
  - deploy

variables:

  AWS_DEFAULT_REGION: 'us-east-1'
  S3_BUCKET: 'tcastel-object-detection'
  MODEL: 'tiny'  
  #normal,tiny

deployement:
  stage: deploy
  image: softinstigate/serverless:latest
  script:
    - serverless deploy --bucket_name $S3_BUCKET --verbose
  environment: production


#unit-test:
#  stage: test
#  image: python:3.7.5
#  before_script:
#    - python --version
#    - pip install virtualenv
#    - virtualenv -p python venv
#    - source venv/bin/activate
#    - pip install -r requirements.txt
#  script:
#    - python3 -m modules.tests.tests -v